### PR TITLE
Add PayPal Terms of Service document (EU EN)

### LINKED ISSUE #50: Add PayPal - User Consent Policy
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/fr/contribute/service?documentType=User%20Consent%20Policy&expertMode=true&name=PayPal&removedCss[]=.header-top&selectedCss[]=%23main&step=2&url=https%3A%2F%2Fwww.paypal.com%2Ffr%2Fwebapps%2Fmpp%2Fua%2Fuseragreement-full%3Flocale.x%3Den_FR&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "PayPal",
  "documents": {
    "User Consent Policy": {
      "fetch": "https://www.paypal.com/fr/webapps/mpp/ua/useragreement-full?locale.x=en_FR",
      "select": [
        "#main"
      ],
      "remove": [
        ".header-top"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/PayPal.json`

Transfered from https://github.com/ambanum/OpenTermsArchive/issues/693

### PR DESCRIPTION
**Pull request by Kissaki**
Closes #50

### CODE REVIEW

**Review by martinratinaud — APPROVED** [review]
Hi @Kissaki and thanks again for the contribution.

I reworked a bit the `startAfter` selector in order to use the specific first `header` within the `#main` section

This will make sure the selector will not change in case a `header` is added in the nev bar for example.

I also copy here a [link to the contribution tool](https://contribute.opentermsarchive.org/service?destination=OpenTermsArchive%2Fcontrib-declarations&expertMode=true&json=%7B%22name%22%3A%22PayPal%22%2C%22documents%22%3A%7B%22Terms%20of%20Service%22%3A%7B%22fetch%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fcz%2Fwebapps%2Fmpp%2Fua%2Fuseragreement-full%3Flocale.x%3Den_CZ%22%2C%22select%22%3A%5B%7B%22startAfter%22%3A%22%23main%20%3E%20header%22%2C%22endBefore%22%3A%22footer%22%7D%5D%7D%7D%7D) to easily validate the declaration.


By the way, using it to contribute has several benefits, such as:

- include a direct link to the contribution tool in the PR, which provides a way to generate the version and see that was is eimed to be tracked is correct
- A visual feedback on selectors (which helped me find out that the `startAfter` selector was targeting several elements on the page) 
- PR title coherence
- Creation of the [history file](https://github.com/OpenTermsArchive/contrib-declarations/blob/main/CONTRIBUTING.md#service-history) when needed

Thanks

**Comment by MattiSG** [comment]
> This will make sure the selector will not change in case a `header` is added later on (in the nav bar for example).

…but this will break in case the `#main` section ID is changed 😉 For me, it is not very clear which of the two was most future-proof. I think both are valid and I would go with the simpler one in that case 🙂

I'm a bit surprised by the inclusion of the “About Your Account” header, but then again this is what the service provider decides to use as a title.

I seem to have as good results with using just `"select": ".ua-container"`, which I find significantly simpler than a range selector. Am I missing something here? 🙂

**Comment by martinratinaud** [comment]
For the `ua-container`, I don't know if it is a stable container or not as I do not know what `ua` stands for, so I guess it's better to keep what's between `header` and `footer`. Also if something is added outside of this `ua-container` (which seems unlikely at that point though), we will catch it.

Please feel free to change the selector if you wish then by resubmitting from [there](https://contribute.opentermsarchive.org/service?destination=OpenTermsArchive%2Fcontrib-declarations&expertMode=true&json=%7B%22name%22%3A%22PayPal%22%2C%22documents%22%3A%7B%22Terms%20of%20Service%22%3A%7B%22fetch%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fcz%2Fwebapps%2Fmpp%2Fua%2Fuseragreement-full%3Flocale.x%3Den_CZ%22%2C%22select%22%3A%5B%7B%22startAfter%22%3A%22%23main%20%3E%20header%22%2C%22endBefore%22%3A%22footer%22%7D%5D%7D%7D%7D)

**Comment by MattiSG** [comment]
I don't mind so much, at that stage I feel that the “maintainability” of selectors has not been very clearly established (beyond obviously machine-generated identifiers such as `.b2n4mdfk23` being bad as they are likely to be dynamic and thus to change on the next website update), so this seems to me to be more of a personal opinion thing, and I'd rather avoid getting stuck in a tabs vs spaces debate 😄

I am more excited about tracking more documents, this PR does just that, so let's merge it 🚀 we'll see if it needs further intervention later, in any case this is already a significant improvement for which we can thank @Kissaki 🙏

I also take note that the need for commonly established guidelines on choosing selectors increases. I hope to lead such a discussion in the next weeks then 🙂

**Comment by Kissaki** [comment]
> I reworked a bit the startAfter selector in order to use the specific first header within the #main section.
>
> This will make sure the selector will not change in case a header is added later on (in the nav bar for example).

Why does this apply to header but not footer?

**Comment by Kissaki** [comment]
Yeah, I used the contibute tool for selector preview.

Using the contributor tool means not preserving author information though, as far as I could tell?

**Comment by Kissaki** [comment]
> I seem to have as good results with using just "select": ".ua-container", which I find significantly simpler than a range selector.

I used the before and after selectors in this PR after a previous PR was changed to them.

being able to use after header before footer seemed quite nice in this case.

It’s probably not worth preparing for structure changes too much. What may change is a guessing game.
I would expect the header footer to remain most stable, and .ua-container second to that (maybe they will switch to a `main` at some point?).

If you are looking to implement and document guidelines, I think they should - or I would

1. Acknowledge the subjectivity/vagueness of selectors depending on structure
2. Possibly document expectation as levels of expected change frequency

My expectation from most stable to least (if they exist) would be (spontaneously)

1. main 
2. header content element and footer
3. specific id or class names on content block that indicates main content block
4. id or class name that looks hand/human picked
5. generated class or id

I think defining more specific guidelines would be difficult.
Documenting what content management systems use may be possible but probably not worth the effort (they may change too).

Thinking about how specific selectors should be may be wasted effort as that is making assumptions without much to base on.
Taking a simple approach and focusing on making the break and fix workflow work well seems better to me.

**Comment by martinratinaud** [comment]
> Yeah, I used the contibute tool for selector preview.
> 
> Using the contributor tool means not preserving author information though, as far as I could tell?

Indeed, this is not yet the case and I will work on it today as it's definitely something we need.
I created [this issue](https://github.com/OpenTermsArchive/contribution-tool/issues/134) just for it.

Thanks again, this feature will be of great benefit for all contributors.

**Comment by martinratinaud** [comment]
> > I seem to have as good results with using just "select": ".ua-container", which I find significantly simpler than a range selector.
> 
> I used the before and after selectors in this PR after a previous PR was changed to them.
> 
> being able to use after header before footer seemed quite nice in this case.
> 
> It’s probably not worth preparing for structure changes too much. What may change is a guessing game. I would expect the header footer to remain most stable, and .ua-container second to that (maybe they will switch to a `main` at some point?).
> 
> If you are looking to implement and document guidelines, I think they should - or I would
> 
> 1. Acknowledge the subjectivity/vagueness of selectors depending on structure
> 2. Possibly document expectation as levels of expected change frequency
> 
> My expectation from most stable to least (if they exist) would be (spontaneously)
> 
> 1. main
> 2. header content element and footer
> 3. specific id or class names on content block that indicates main content block
> 4. id or class name that looks hand/human picked
> 5. generated class or id
> 
> I think defining more specific guidelines would be difficult. Documenting what content management systems use may be possible but probably not worth the effort (they may change too).
> 
> Thinking about how specific selectors should be may be wasted effort as that is making assumptions without much to base on. Taking a simple approach and focusing on making the break and fix workflow work well seems better to me.

Hi @Kissaki, the guidelines you're suggesting are a very good starting point and I thank you much for that.
As discussed with @MattiSG, we will start a new discussion about this topic soon so that contributions become easier and easier.

I also believe the "break and fix workflow" part is critical and we continuously try to improve it. We welcome any suggestions you might have by the way :-)

**Comment by MattiSG** [comment]
Thank you so much @Kissaki for your writeup! I opened a [dedicated discussion](https://github.com/ambanum/OpenTermsArchive/discussions/960) on this topic. Would you mind sharing your thoughts there? 😃

**Pull request merged**
