### PR TITLE
Fix Facebook ToS and PP

### LINKED ISSUE #634: Fix Facebook - Privacy Policy
This document is no longer properly tracked.

`InaccessibleContentError: The document cannot be accessed or its content can not be selected: The provided selector "._5tkp" has no match in the web page at 'https://www.facebook.com/about/privacy'`

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fcontrib-declarations&step=2&url=https%3A%2F%2Fwww.facebook.com%2Fabout%2Fprivacy&name=Facebook&documentType=Privacy%20Policy&selectedCss[]=._5tkp&expertMode=true).
- Using the [local contribution tool](http://localhost:3000/en/service?destination=OpenTermsArchive%2Fcontrib-declarations&step=2&url=https%3A%2F%2Fwww.facebook.com%2Fabout%2Fprivacy&name=Facebook&documentType=Privacy%20Policy&selectedCss[]=._5tkp&expertMode=true). See [Setup Guide](https://github.com/OpenTermsArchive/contribution-tool#usage).

And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/contrib-declarations/blob/main/declarations/Facebook.json).

### PR DESCRIPTION
**Pull request by martinratinaud**
Closes #634

### CODE REVIEW

**Comment by martinratinaud** [comment]
Merge without review as it's the same change as on france-elections and receiving emails on every process is a real pain

**Comment by MattiSG** [comment]
The change in https://github.com/OpenTermsArchive/contrib-declarations/pull/647 was not reviewed.

**Comment by martinratinaud** [comment]
I think you did not put the right link @MattiSG as this one points to this very PR

**Comment by MattiSG** [comment]
Oh no, you're right, thanks for pointing it out! I meant that https://github.com/OpenTermsArchive/france-elections-declarations/pull/162 had not been reviewed, hence copying it here without a review duplicated a change that did need further work (cf. https://github.com/OpenTermsArchive/france-elections-declarations/pull/163 and the ongoing discussion in https://github.com/OpenTermsArchive/france-elections-declarations/pull/162).

**Pull request merged**
