### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by emmanuellar**
Create CONTRIBUTING.md and outline some introductory notes for hacktoberfest participants.

### CODE REVIEW

**Comment by emmanuellar** [comment]
Some things I'd like to clarify regarding this PR @OpenTermsArchive/core 
-  I was unable to locate the code of conduct in the root folder, but I went ahead to send in a PR with placeholder links in order not to drag the draft submission.
- I wasn't sure how contributors will let us know they're working on an issue. In Clifford's doc, he suggested self-assignment, but I'd like to confirm if this is what we're still going by.
- The last point in the "how to contribute" is only an idea, and can be removed if not bought.

Thank you.

**Comment by Kissaki** [comment]
The README has a very short *contributing* section that simply points to the *contributing terms*. I do not see any link to that in the suggested CONTRIBUTING file?

October is almost over. Dunno how fast your responses will be, but I would consider dropping the issue assignment, video, and code of conduct references to merge ASAP. Those questions can be suggested and discussed afterward too. Otherwise, I feel like the Hacktoberfest mentions become (even more) pointless - assuming they will be removed after October.

**Review by Cli4d — COMMENTED** [review]
Hi @emmanuellar,

Thank you for creating the Contributing file. However, I think it would be best if we left out the video section due to time constraints. Additionally, I suggest that we include only a brief section on hacktoberfest at the bottom of the document, rather than dedicating the entire file to it. 
Let me make the changes and merge it
 

Thank you,

**Review by Cli4d — APPROVED** [review]
I have made some changes based on the feedback provided by @Kissaki's and my own opinions. I have tried to make it less dependent on Hacktoberfest, only mentioning it briefly in a small section that we can remove later. For now, I will proceed to merge it, but we can always make further modifications in the future.

**Pull request merged**
