### PR TITLE
Make google play filters runnable in browser - updated

### PR DESCRIPTION
**Pull request by Ndpnt**
Proposal replacement for https://github.com/OpenTermsArchive/contrib-declarations/pull/625. 

Replace deprecated function and remove obsolete dependency and associated code.

### CODE REVIEW

**Comment by Ndpnt** [comment]
@LVerneyPEReN Can you check this PR and confirm that it works for you?

**Review by martinratinaud — APPROVED** [review]

**Comment by LVerneyPEReN** [comment]
@Ndpnt Unless I missed something, `Buffer` is not available in browser (at least Firefox ESR).

**Comment by Ndpnt** [comment]
> @Ndpnt Unless I missed something, `Buffer` is not available in browser (at least Firefox ESR).

My bad, you're right. I rollback to your version and just remove obsolete dependency and associated code.

**Comment by LVerneyPEReN** [comment]
Thanks!

**Pull request merged**
