### PR TITLE
Track Blockworks

### PR DESCRIPTION
**Pull request by afisher3578**

### CODE REVIEW

**Comment by afisher3578** [comment]
Chose Editorial Policy as the terms type based on this discussion: https://github.com/OpenTermsArchive/terms-types/discussions/35

**Comment by clementbiron** [comment]
Thanks Alex,

@OpenTermsArchive/core we need to update the terms types version to [1.3.0](https://github.com/OpenTermsArchive/terms-types/releases/tag/v1.3.0) in this collection to handle that contribution.

**Comment by Ndpnt** [comment]
> @OpenTermsArchive/core we need to update the terms types version to [1.3.0](https://github.com/OpenTermsArchive/terms-types/releases/tag/v1.3.0) in this collection to handle that contribution.

@clementbiron can you handle it?

**Review by clementbiron — APPROVED** [review]
Thanks Alex!

**Pull request merged**
