### PR TITLE
Update Pinterest pp & tos

### PR DESCRIPTION
**Pull request by afisher3578**

### CODE REVIEW

**Review by clementbiron — APPROVED** [review]
Thanks Alex for this correction! I've updated the `validUnti`l date, which didn't seem right, and I'd be happy to talk to you about it if you'd like.

**Comment by afisher3578** [comment]
Hey, thank you for updating the `validUntil`date. I took the date that was referenced in the issues for all of my latest pull requests so they are all probably wrong. Where did you find the correct date so I know where to look in the future?

**Comment by clementbiron** [comment]
Hi Alex,

You're right to ask and I should have explained in my first comment, sorry. It shows us once again that our documentation on this subject is not quite complete and that it deserves to be improved. 

In any case, I retrieved the date of `valitUntil` by doing the following: 

1. first I go to the [open issue](https://github.com/OpenTermsArchive/contrib-declarations/issues/1234) and position myself on the [last comment](https://github.com/OpenTermsArchive/contrib-declarations/issues/1234#issuecomment-2125994885) from OTA-Bot

2. on the date of this comment I right-click "inspect" (on this case, the date is not quite precise, it's "last month")
image

3. I copy the value of the `datetime` attribute from the `<relative-time>` element
image

I hope this helps and don't hesitate to ask for clarification !

**Comment by afisher3578** [comment]
@clementbiron Thank you for the detailed explanation, that clears up my question!

**Pull request merged**
