### PR TITLE
Stop Facebook Blinking: Data Processor Agreement & Live Policy

### PR DESCRIPTION
**Pull request by afisher3578**
I saw that the bottom menu on both of these pages were causing the blinking so I created a new filter to remove it. I also had to remove the 'remove' property from Data Processor Agreement to still display all of the content. 

This ran well locally, but let me know if this is structured correctly and if need any changes. Thanks.

### CODE REVIEW

**Comment by martinratinaud** [comment]
Hi @afisher3578. I'm truly sorry about that.
A recent update made the CI break and will be fixed today with https://github.com/OpenTermsArchive/contrib-declarations/pull/577.

Once this is merged, you will just need to rebase on `main` and force push your branch

**Review by clementbiron — CHANGES_REQUESTED** [review]
Thanks Alex for this PR!

I've suggested some changes, don't hesitate to ask me for clarification if it's not clear enough.

And I think you forgot to update the history file (you'll find some documentation [here](https://github.com/OpenTermsArchive/contrib-declarations/blob/main/CONTRIBUTING.md#service-history)).

**Comment by afisher3578** [comment]
Hi @clementbiron thanks for the recommendations, I added those changes.

I also updated the history file but I was a little confused with the documentation. Where do I find the date for the latest snapshot commit? I added the changes to history but still need to update the new validUntil date.

**Comment by Ndpnt** [comment]
Thanks @afisher3578 for your fix.
It's currently a bit of a pain to find the `validUntil` date. You have to browse through the snapshots and find the last snapshot for which the declaration is still valid, and that is the date of that snapshot. As on this instance the snapshots are not publicly available, and as we need to create tools to make it easier to find the `validUntil` value, for now I suggest using, as an approximation, the date of the last valid version.

**Comment by afisher3578** [comment]
Thanks @Ndpnt for the help. I updated the history file based on the last valid versions so it should be all good now.

**Comment by clementbiron** [comment]
Thank you and congratulations, documents maintenance is not always easy!

One last thing, it would be better to include the changes on Reddit in another PR.

**Comment by afisher3578** [comment]
Hi @clementbiron I saw that I commited my reddit changes to this PR when I meant to start a new branch. I am trying to get that fixed right now without messing up this PR.

**Comment by martinratinaud** [comment]
> Thanks @afisher3578 for your fix. It's currently a bit of a pain to find the `validUntil` date. You have to browse through the snapshots and find the last snapshot for which the declaration is still valid, and that is the date of that snapshot. As on this instance the snapshots are not publicly available, and as we need to create tools to make it easier to find the `validUntil` value, for now I suggest using, as an approximation, the date of the last valid version.

For information also
The [contribution tool](https://github.com/OpenTermsArchive/contribution-tool), when installed in local, can create automatically the history file for you with this `validUntil` key.

Do not hesitate to contact me if you need help on setting this up

**Comment by Ndpnt** [comment]
Hi @afisher3578, I saw in your git history that there are merge commits and commits not related to the purpose of this PR which remove work from another document update. 
To have a cleaner history and facilitate peer reviews, we follow the [GitHub flow](https://docs.github.com/en/get-started/quickstart/github-flow) branching model. We create a branch from the `main` branch for each document/service we want to update, add some commits to update the document and then create a pull request with this branch. And to avoid merge commits in our history when our branch is out of date with the `main`, we use git rebase command.

Could you update your history to only have commits related to Facebook documents update? 

We may have a call if you need help with git, just let me know :).

**Pull request closed without merging**
